version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "7000:7000"
    environment:
      LISTEN_HOST: "0.0.0.0"
      LISTEN_PORT: "7000"
      ALLOWED_ORIGINS: "http://localhost:8000"
  frontend:
    build: ./frontend
    ports:
      - "8000:5173"
    environment:
      AUTOSUGGEST_API_URL: "http://localhost:7000"
